const MIMES = [
'application/mp4; codecs=bogus',
'application/mp4',
'application/octet-stream; codecs=bogus',
'application/octet-stream',
'application/ogg; codecs=bogus',
'application/ogg',
'audio/3gpp',
'audio/3gpp2',
'audio/aac',
'audio/ac3',
'audio/aiff',
'audio/basic',
'audio/flac',
'audio/mid',
'audio/midi',
'audio/mp3',
'audio/mp4; codecs=bogus',
'audio/mp4',
'audio/mpeg',
'audio/mpeg',
'audio/mpegurl',
'audio/ogg; codecs=bogus',
'audio/ogg; codecs=flac',
'audio/ogg; codecs=opus',
'audio/ogg; codecs=speex',
'audio/ogg; codecs=vorbis',
'audio/ogg',
'audio/vnd.wave; codecs=1',
'audio/vnd.wave',
'audio/wav; codecs=0',
'audio/wav; codecs=1',
'audio/wav; codecs=2',
'audio/wav',
'audio/wave; codecs=0',
'audio/wave; codecs=1',
'audio/wave; codecs=2',
'audio/wave',
'audio/webm; codecs=vorbis',
'audio/webm',
'audio/x-aac',
'audio/x-ac3',
'audio/x-aiff',
'audio/x-flac',
'audio/x-midi',
'audio/x-mp3',
'audio/x-mpeg',
'audio/x-mpeg',
'audio/x-mpegurl',
'audio/x-pn-wav; codecs=0',
'audio/x-pn-wav; codecs=1',
'audio/x-pn-wav; codecs=2',
'audio/x-pn-wav',
'audio/x-wav; codecs=0',
'audio/x-wav; codecs=1',
'audio/x-wav; codecs=2',
'audio/x-wav',
'video/3gpp; codecs="mp4v.20.8, samr"',
'video/3gpp',
'video/3gpp2',
'video/avi',
'video/hevc',
'video/mp4 ; CODECS="mp4v.20.8, mp4a.40.2"',
'video/mp4; codecs="avc1.42E01E, mp4a.40.2"',
'video/mp4; codecs="avc1.42E01E"',
'video/mp4; Codecs="avc1.4D400C"',
'video/mp4; codecs="avc1.4D401E, mp4a.40.2"',
'video/mp4; codecs="avc1.58A01E, mp4a.40.2"',
'video/mp4; codecs="avc1.64001E, mp4a.40.2"',
'video/mp4; codecs="avc3"',
'video/mp4; codecs="mp4v.20.240, mp4a.40.2"',
'video/mp4; codecs="mp4v.20.8, mp4a.40.2"',
'video/mp4; codecs=bogus',
'video/mp4',
'video/mpeg',
'video/msvideo',
'video/ogg; codecs="dirac, vorbis"',
'video/ogg; codecs="theora, speex"',
'video/ogg; codecs="theora, vorbis"',
'video/ogg; codecs=bogus',
'video/ogg; codecs=theora,vorbis',
'video/ogg; codecs=theora',
'video/ogg',
'video/quicktime',
'video/webm; codecs="vp8, vorbis"',
'video/webm; codecs=vorbis',
'video/webm; codecs=vp8.0',
'video/webm; codecs=vp8',
'video/webm',
'video/x-m4v',
'video/x-matroska; codecs="theora, vorbis"',
'video/x-mpeg',
'video/x-msvideo']

export default MIMES;